### ISSUE TITLE
`NetworkReplicator::SetObjectOwnership` is actually deferred by 1 frame for objects spawned dynamically with `NetworkReplicator::SpawnObject`

### ISSUE THREAD

**Issue by Withaust** [FlaxEngine/FlaxEngine#1066]
**Issue description:**
Currently, if you were going to use `NetworkReplicator::SetObjectOwnership` on a dynamically spawned object with `NetworkReplicator::SpawnObject` and would try to write some init logic in a script that relies on a pre-set authority - you wont be able to do that consistently. For newly spawned objects `NetworkReplicator::SetObjectOwnership` is going to `really` set their authority only on the next update frame after sending them all out. This problem forces to write hacky code with manual ownership handling, due to delayed propagation from `NetworkReplicator::SetObjectOwnership`.

**Steps to reproduce:**
Use `NetworkReplicator::SetObjectOwnership`, and try writing some init code that is reliant on object ownership, something like:
If we own object, then set current actors name to "Local".

**Flax version:**
Flax 1.5.6338 on Windows 10 x64

**Comment by mafiesto4** [comment]
I did fixes for this in: 0a5d37fd9b3cb8c9fafd1f6906dbac61afb00e82 and 531d0051696b01c3952e0b3a2cb61e2e5bcf5919.

Here is an example script I tried and it works fine now (spawns object from server that is owned by client):
```cs
public class TestSetObjectOwnership : Script
{
    /// <inheritdoc />
    public override void OnUpdate()
    {
        if (!NetworkManager.IsClient && Input.GetKeyDown(KeyboardKeys.G))
        {
            // Create new object
            var newObject = new EmptyActor();
            var newScript = newObject.AddScript<ObjectRename>();
            newObject.Parent = Scene;

            // Network spawn
            var clients = NetworkManager.Clients;
            var owner = clients.Length != 0 ? clients[0] : NetworkManager.LocalClient;
            NetworkReplicator.SpawnObject(newObject);
            NetworkReplicator.SpawnObject(newScript);
            NetworkReplicator.SetObjectOwnership(newObject, owner.ClientId, NetworkObjectRole.None);
        }
    }
}

public class ObjectRename : Script
{
    /// <inheritdoc />
    public override void OnEnable()
    {
        Actor.Name = "Object Ownership";
        if (NetworkReplicator.IsObjectOwned(Actor))
            Actor.Name += " (owned)";
    }
}
```

If you still have an issue with this feel free to share a sample script to reproduce your problem, otherwise I hope this issue can be closed.

**Comment by Withaust** [comment]
@mafiesto4 Current implementation of `SetObjectOwnership` returns prematurely at line 947 
![image](https://user-images.githubusercontent.com/118038102/236705600-4d90bb01-c0c7-41b6-bbe8-d048b0276f7c.png)
when it could not find objects in a replicated Dictionary, so if you, for example have a `hierarchical` set to `true` (like I do), it would only set ownership to the first object and would give up afterwards

**Comment by Withaust** [comment]
This is exactly the same issue as with the original code. If you were going to spawn an actor from a prefab and try to hierarchicaly assign ownership, then if you had any initialization logic inside components attached to the actor they would get `None`

**Comment by mafiesto4** [comment]
It should be fixed in 953ae3e9bbbfd9d353bd7d2b0b390edbf784b308.

Here is an example setup I tested (`ObjectRename` was added to various objects in prefab):

```cs
public class TestSetObjectOwnership : Script
{
    public Prefab MyPrefab;

    public override void OnUpdate()
    {
        if (!NetworkManager.IsClient && Input.GetKeyDown(KeyboardKeys.G))
        {
            // Create prefab instance
            var instance = PrefabManager.SpawnPrefab(MyPrefab, null);

            // Network spawn with the first client as an owner
            var clients = NetworkManager.Clients;
            var owner = clients.Length != 0 ? clients[0] : NetworkManager.LocalClient;
            NetworkReplicator.SpawnObject(instance);
            NetworkReplicator.SetObjectOwnership(instance, owner.ClientId);

            // Local spawn
            Level.SpawnActor(instance);
        }
    }
}

public class ObjectRename : Script
{
    public override void OnEnable()
    {
        NetworkReplicator.AddObject(this);

        Actor.Name += $" ({NetworkReplicator.GetObjectRole(this)})";
    }

    public override void OnDisable()
    {
        NetworkReplicator.RemoveObject(this);
    }
}
```

To make this easier to inspect I added network object debugger in Editor e045f096a9dbe635ad02548155b30e61ea842812:

![image](https://github.com/FlaxEngine/FlaxEngine/assets/3464853/d1d81642-7f87-4880-aff1-bc51f8e64f42)

**Comment by Withaust** [comment]
Just tested it, this issue now seems to be resolved.

**Comment by Withaust** [comment]
There was an issue that I found with https://github.com/FlaxEngine/FlaxEngine/commit/953ae3e9bbbfd9d353bd7d2b0b390edbf784b308, but here is a PR to fix it -> https://github.com/FlaxEngine/FlaxEngine/pull/1105

**Comment by Withaust** [comment]
It seems that the problem is still present. Let me try explaining again what I mean.

Here, we have an ownership assignment for objects in the spawn queue:
https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Networking/NetworkReplicator.cpp#L965-L992
and here is the ownership assignment for objects that are already present in the replicated dictionary:
https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Networking/NetworkReplicator.cpp#L994-L1019

This is all great, but when it comes to the hiearchical assignment here:
https://github.com/FlaxEngine/FlaxEngine/blob/master/Source/Engine/Networking/NetworkReplicator.cpp#L1022-L1029
it does not actually consider objects in the spawn queue and only tries to work on replicated dictionary, resulting initial assignment of the target object succeeding, but skipping an assignment for all other child objects sitting in the spawn queue.

**Comment by Withaust** [comment]
I have made a PR that fixes this issue that I have described above -> https://github.com/FlaxEngine/FlaxEngine/pull/1106

**Comment by mafiesto4** [comment]
Merged. Thanks for spotting this problem and helping to solve it 🎉
