### ISSUE TITLE
[Bug, Fog, Large-World Origin Shift] Height Fog does not properly account for world origin shift

### ISSUE THREAD

**Issue by GasimoCodes** [FlaxEngine/FlaxEngine#3443]
When the camera moves far enough for the origin to shifts, height fog gets moved too, (presumably) causing a sudden change in density.

https://github.com/user-attachments/assets/6e3ef48f-67b0-474b-ba2e-a941f7aa360e

**Comment by mafiesto4** [comment]
Fixed in 47711ec5bebfabf1bd71baca76f9727d020deba1.

**Comment by GasimoCodes** [comment]
I have managed to replicate the behaviour again on new master large worlds. 
When moving the camera up/down the fog still cuts. Maybe this is related to origin shifting and the height fog density not accounting for it?

https://github.com/user-attachments/assets/98fbe12c-495d-4497-9c00-fb48eefb8f1c

**Comment by mafiesto4** [comment]
Another fix in 6ae370f8fc6e7377016d3e79813b4b3634244933.

**Comment by GasimoCodes** [comment]
Super sorry to be poking here again but updating to the most recent commit today it seems that the issue is still present when flying upwards and crossing origin shift boundaries. @mafiesto4 

https://github.com/user-attachments/assets/dba303be-526b-42d2-811e-ae246c3ad9fe

**Comment by mafiesto4** [comment]
Fixed fog flickering when moving up/down in: cc51ae4562d9ee4f94db8cf905e51a767f83ecac
