### ISSUE TITLE
[Bug]: Unable to attach an actor to script inherited from another script

### ISSUE THREAD

**Issue by Retr0-code** [FlaxEngine/FlaxEngine#3704]
### Description

I am making a hierarchical state machine. States are attached to an actor and all of them inherit from `IState` class with public fields `AnimatedModel` and `Animation`. I've tried using setters and getters, but the same problem occurs. After attaching required actors and assets, links disappear when running a scene in the editor. The issue consistently reproduces every time

P.S. Attaching only sources, because any basic project exceeds 10MB limit

[Game-src.zip](https://github.com/user-attachments/files/22603897/Game-src.zip)

### Steps to reproduce

1. Add a base class (e.g. IState);
```cpp
#pragma once

#include "Engine/Scripting/Script.h"
#include "Engine/Level/Actor.h"

API_CLASS() class GAME_API IState : public Script
{
DECLARE_SCRIPTING_TYPE(IState);

	API_FIELD(Public) Actor* Model = nullptr;

	API_FUNCTION()
	virtual IState* Process(float deltaTime);

	void OnEnable() override;

	void OnDisable() override;
};
```

2. Add a inherited class (e.g. StateIdle);
```cpp
#pragma once

#include "IState.h"

API_CLASS() class GAME_API StateIdle :  public IState
{
API_AUTO_SERIALIZATION();
DECLARE_SCRIPTING_TYPE(StateIdle);

	IState* Process(float deltaTime) override;
};
```

3. Attach both scripts to the same actor;
4. Play in editor;

### Version

master branch

### Relevant logs

```shell

```

**Comment by Tryibion** [comment]
Hello, for referencing a scene object, it is best practice to use the `ScriptingObjectReference<>` wrapper for the reference to serialize correctly.

Is the issue that the reference is being cleared when you play in the editor, then using `ScriptingObjectReference<Actor>` instead of `Actor*` should fix that.

**Comment by Retr0-code** [comment]
Thank You for the suggestion, I've changed pointers to corresponding wrappers
```cpp
API_FIELD(Public) ScriptingObjectReference<Actor> Model = nullptr;
API_FIELD(Public) AssetReference<Animation> Animation = nullptr;
```
and unfortunately both of them have produced the exact same behaviour as pointers

**Comment by Tryibion** [comment]
Hmmm, maybe it has something to do with just using the `Public` API tag. If you make those variables protected or public using the regular c++ style instead of API tag, does that make a difference?

**Comment by Retr0-code** [comment]
While `API_FIELD(Public)` exposes a member variable to editor, default public and protected modifier don't. This leads to use of  setters and getters with `API_PROPERTY` macro and the problem remains

Edit: I can't even use setters and getters without `API_FIELD` macro in definition of member variables

**Comment by Tryibion** [comment]
This works fine for me. serializes fine and keeps the values. to expose to the editor an API tag is needed.

```
API_CLASS() class GAME_API IState : public Script
{
API_AUTO_SERIALIZATION();
DECLARE_SCRIPTING_TYPE(IState);

public:
    API_FIELD() ScriptingObjectReference<Actor> Model;
    API_FIELD() AssetReference<Animation> Animation;

protected:
    // [Script]
    void OnEnable() override;
    void OnDisable() override;
    void OnUpdate() override;
};
```

```
API_CLASS() class GAME_API IdleState : public IState
{
API_AUTO_SERIALIZATION();
DECLARE_SCRIPTING_TYPE(IdleState);
    
protected:
    // [Script]
    void OnEnable() override;
    void OnDisable() override;
    void OnUpdate() override;
};
```

**Comment by Retr0-code** [comment]
Thank You so much, this solution worked for me
